approvedGitRepositories:
  - "**"

checksumBehavior: throw

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
